In [1]:
from keras import Sequential

Using TensorFlow backend.


In [2]:
model=Sequential()

In [3]:
from keras.layers import Dense

In [4]:
model.add(Dense(units=1,input_shape=(6,)))

Instructions for updating:
Colocations handled automatically by placer.


In [5]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 7         
Total params: 7
Trainable params: 7
Non-trainable params: 0
_________________________________________________________________


In [6]:
from keras.optimizers import Adam,SGD

In [7]:
model.compile(Adam(),loss="mean_squared_error")

In [8]:
import pandas as pd

In [9]:
df=pd.read_csv('50_Startups.csv')

In [10]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [11]:
y=df['Profit']
import numpy

In [12]:
Y=numpy.array(y)

In [13]:
Y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [14]:
x=df[['R&D Spend','Administration','Marketing Spend','State']]

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
encode_x=LabelEncoder()

In [18]:
x4=x.iloc[:,-1]

In [19]:
x4

0       New York
1     California
2        Florida
3       New York
4        Florida
5       New York
6     California
7        Florida
8       New York
9     California
10       Florida
11    California
12       Florida
13    California
14       Florida
15      New York
16    California
17      New York
18       Florida
19      New York
20    California
21      New York
22       Florida
23       Florida
24      New York
25    California
26       Florida
27      New York
28       Florida
29      New York
30       Florida
31      New York
32    California
33       Florida
34    California
35      New York
36       Florida
37    California
38      New York
39    California
40    California
41       Florida
42    California
43      New York
44    California
45      New York
46       Florida
47    California
48      New York
49    California
Name: State, dtype: object

In [20]:
x4_new=encode_x.fit_transform(x4)

In [21]:
x4_new

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0])

In [22]:
x['State']=x4_new

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [23]:
Ohe=OneHotEncoder(categorical_features=[-1])

In [24]:
X=Ohe.fit_transform(x).toarray()

/usr/local/lib64/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib64/python3.6/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [38]:
model.fit(X,Y,epochs=50)

Epoch 1/50
50/50 [==============================] - 0s 402us/step - loss: 96720056811.5200
Epoch 2/50
50/50 [==============================] - 0s 171us/step - loss: 96210890915.8400
Epoch 3/50
50/50 [==============================] - 0s 209us/step - loss: 95664454696.9600
Epoch 4/50
50/50 [==============================] - 0s 212us/step - loss: 95128972820.4800
Epoch 5/50
50/50 [==============================] - 0s 277us/step - loss: 94624672645.1200
Epoch 6/50
50/50 [==============================] - 0s 160us/step - loss: 94080069468.1600
Epoch 7/50
50/50 [==============================] - 0s 68us/step - loss: 93549498859.5200
Epoch 8/50
50/50 [==============================] - 0s 204us/step - loss: 93057748828.1600
Epoch 9/50
50/50 [==============================] - 0s 67us/step - loss: 92532722892.8000
Epoch 10/50
50/50 [==============================] - 0s 303us/step - loss: 91994600898.5600
Epoch 11/50
50/50 [==============================] - 0s 69us/step - loss: 91529111961.6000


In [39]:
y_pred=model.predict(X)

In [40]:
W,B=model.get_weights()

In [41]:
W

array([[ 0.95846456],
       [ 0.83743465],
       [-0.18434082],
       [-0.308322  ],
       [ 0.5261706 ],
       [-0.7673599 ]], dtype=float32)

In [42]:
B

array([0.12477601], dtype=float32)

In [43]:
from sklearn.metrics import r2_score

In [44]:
from sklearn.metrics import r2_score
print("The R2 score is {:0.3f}".format(r2_score(Y, y_pred)))

The R2 score is -44.921
